server:
  port: 8080

spring:
  application:
    name: media-pipeline-lite
  datasource:
    url: jdbc:h2:mem:mediadb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
    exposure:
      include: health,prometheus,metrics